# Made with a <3 from Kristoffer #

target:
  ## X-Z radius from player
  mob-target-radius: 42
  ## Y difference from player
  mob-target-height: 5

  ## In ms, (lower = worse performance)
  mob-target-delay: 2000